feat: 增加react规则
explore-frontend/basic-configs pull request #1
Opened 2023-04-21 09:42 UTC by trptrp

2023-04-21 11:06 UTC, Amorites commented
另外再额外建一个preset吧，可以参考现在preset文件夹里的内容

2023-04-21 11:07 UTC, Amorites requested changes

2023-04-21 11:07 UTC, Amorites commented on packages/eslint-config/react.js
> +p// @ts-check
p(

2023-04-21 11:07 UTC, Amorites commented on packages/eslint-config/react.js
> +    rules: {
非 react 的规则就不要写在这了

2023-04-21 11:07 UTC, Amorites commented on package.json
> +    "eslint-config-alloy": "^4.5.1",
这些依赖不应该直接改根目录的 package.json，去具体的pakcage里面加吧

2023-04-21 11:07 UTC, Amorites commented on packages/eslint-config/react.js
> +                objectLiteralTypeAssertions: 'allow',
这里为啥是 allow

2023-04-21 11:07 UTC, Amorites commented on packages/eslint-config/react.js
> +        'max-params': [2, { max: 6 }],
这个规则跟 @xiaoxiangmoe 确认一下，基础规范最好统一

2023-04-23 02:51 UTC, trptrp commented on packages/eslint-config/react.js
> +                objectLiteralTypeAssertions: 'allow',
这个应该是我们项目改ts时引入的，与react无关，应该移除

2023-04-23 03:00 UTC, trptrp commented on packages/eslint-config/react.js
> +    rules: {
done

2023-04-23 03:01 UTC, trptrp commented on packages/eslint-config/react.js
> +p// @ts-check
done

2023-04-23 03:01 UTC, trptrp commented on package.json
> +    "eslint-config-alloy": "^4.5.1",
done

2023-04-23 03:01 UTC, trptrp commented on packages/eslint-config/react.js
> +        'max-params': [2, { max: 6 }],
确认了react这边没有相关要求，是迁ts时引入的，已经移除

2023-04-23 03:39 UTC, Amorites requested changes

2023-04-23 03:39 UTC, Amorites commented on packages/eslint-config/package.json
> +        "eslint-config-alloy": "^4.5.1",
要不要升级一下

2023-04-23 03:39 UTC, Amorites commented on packages/eslint-config/package.json
> +        "eslint": "^8.24.0",
eslint 已经在 dependencies 出现过了

2023-04-23 03:39 UTC, Amorites commented on packages/eslint-config/package.json
> +        "typescript": "^4.0.0"
typescript 版本要求不太准确，比如5.x是可以支持的

（要不peerDependencies直接去掉吧

2023-04-23 03:39 UTC, Amorites commented on packages/eslint-config/preset/react-ts.js
> +            extends: ['../typescript', '../react'],
javascript 和 typescript-requiring-type-checking 也加一下吧

2023-04-23 04:02 UTC, trptrp commented on packages/eslint-config/package.json
> +        "eslint-config-alloy": "^4.5.1",
试了下似乎向下兼容有问题，凭空多了351errors和81warnings

2023-04-23 04:08 UTC, trptrp commented on packages/eslint-config/package.json
> +        "eslint-config-alloy": "^4.5.1",
ts@5还是有些新的rules，有变化但是好改

2023-04-23 15:28 UTC, trptrp commented
> 另外再额外建一个preset吧，可以参考现在preset文件夹里的内容
done

2023-04-24 02:41 UTC, Amorites approved these changes

2023-04-24 11:24 UTC, xiaoxiangmoe commented on packages/eslint-config/preset/react-ts.js
> +                React: true,
有一个 global 的 React 值好吗？

2023-04-26 03:36 UTC, trptrp commented on packages/eslint-config/preset/react-ts.js
> +                React: true,
的确，还是交给项目比较好

2023-04-26 07:48 UTC, xiaoxiangmoe commented on packages/eslint-config/preset/react-ts.js
> +                node: true,
为什么会 node true

2023-04-26 07:49 UTC, xiaoxiangmoe commented on packages/eslint-config/preset/react-ts.js
> +                node: true,
是不是缺了一个 es2023: true

2023-04-26 08:01 UTC, xiaoxiangmoe commented on packages/eslint-config/preset/react-ts.js
> +            extends: ['../javascript', '../typescript-requiring-type-checking', '../typescript', '../react'],
, '../typescript' 放在 '../typescript-requiring-type-checking', 前面吧

2023-04-28 09:50 UTC, merged